return {
  version = "1.9",
  luaversion = "5.1",
  tiledversion = "1.9.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 30,
  height = 20,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 4,
  nextobjectid = 307,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "Objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "Player",
          class = "",
          shape = "ellipse",
          x = -26.6667,
          y = -42.6667,
          width = 144.167,
          height = 144.167,
          rotation = 0,
          visible = true,
          properties = {
            ["player"] = true
          }
        },
        {
          id = 4,
          name = "",
          class = "",
          shape = "ellipse",
          x = -158,
          y = -129,
          width = 86.5,
          height = 86.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          class = "",
          shape = "ellipse",
          x = 169,
          y = -93,
          width = 50,
          height = 50,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          class = "",
          shape = "ellipse",
          x = 144.5,
          y = 115,
          width = 37,
          height = 37,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          class = "",
          shape = "ellipse",
          x = -170,
          y = 121,
          width = 47.5,
          height = 47.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          class = "",
          shape = "ellipse",
          x = -344,
          y = -49,
          width = 71.5,
          height = 71.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          class = "",
          shape = "ellipse",
          x = 36,
          y = -319,
          width = 44,
          height = 44,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          class = "",
          shape = "ellipse",
          x = 346,
          y = -301,
          width = 37,
          height = 37,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          class = "",
          shape = "ellipse",
          x = 513,
          y = 40,
          width = 75,
          height = 75,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          class = "",
          shape = "ellipse",
          x = 341,
          y = 248,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          class = "",
          shape = "ellipse",
          x = 100,
          y = 272,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          class = "",
          shape = "ellipse",
          x = -290,
          y = 265,
          width = 71,
          height = 71,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          class = "",
          shape = "ellipse",
          x = -542,
          y = 132,
          width = 92,
          height = 92,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          class = "",
          shape = "ellipse",
          x = -522,
          y = -64,
          width = 50,
          height = 50,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          class = "",
          shape = "ellipse",
          x = -324,
          y = -242,
          width = 38,
          height = 38,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          class = "",
          shape = "ellipse",
          x = -163,
          y = -386,
          width = 25,
          height = 25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          class = "",
          shape = "ellipse",
          x = 207,
          y = -527,
          width = 17,
          height = 17,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          class = "",
          shape = "ellipse",
          x = 698,
          y = -284,
          width = 9,
          height = 9,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          class = "",
          shape = "ellipse",
          x = 728,
          y = -66,
          width = 28,
          height = 28,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          class = "",
          shape = "ellipse",
          x = 591,
          y = -46,
          width = 14,
          height = 14,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          class = "",
          shape = "ellipse",
          x = 533,
          y = -32,
          width = 9,
          height = 9,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          class = "",
          shape = "ellipse",
          x = 494,
          y = -12,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          class = "",
          shape = "ellipse",
          x = 448,
          y = 24,
          width = 5,
          height = 5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          class = "",
          shape = "ellipse",
          x = 270,
          y = 95,
          width = 29,
          height = 29,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          class = "",
          shape = "ellipse",
          x = 263,
          y = 172,
          width = 7,
          height = 7,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          class = "",
          shape = "ellipse",
          x = 218,
          y = 239,
          width = 7,
          height = 7,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          class = "",
          shape = "ellipse",
          x = 234,
          y = 268,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          class = "",
          shape = "ellipse",
          x = 249,
          y = 300,
          width = 7,
          height = 7,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          class = "",
          shape = "ellipse",
          x = 56,
          y = 239,
          width = 7,
          height = 7,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          class = "",
          shape = "ellipse",
          x = 30,
          y = 204,
          width = 22,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          class = "",
          shape = "ellipse",
          x = 58,
          y = 173,
          width = 7,
          height = 7,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          class = "",
          shape = "ellipse",
          x = 98,
          y = 156,
          width = 15,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          class = "",
          shape = "ellipse",
          x = 123,
          y = 208,
          width = 19,
          height = 19,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          class = "",
          shape = "ellipse",
          x = 178,
          y = 211,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          class = "",
          shape = "ellipse",
          x = 214,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          class = "",
          shape = "ellipse",
          x = 203,
          y = 96,
          width = 13,
          height = 13,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          class = "",
          shape = "ellipse",
          x = 213,
          y = 52,
          width = 9,
          height = 9,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          class = "",
          shape = "ellipse",
          x = 245,
          y = 25,
          width = 10,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          class = "",
          shape = "ellipse",
          x = 275,
          y = 13,
          width = 17,
          height = 17,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          class = "",
          shape = "ellipse",
          x = 317,
          y = -28,
          width = 21,
          height = 21,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          class = "",
          shape = "ellipse",
          x = 389,
          y = -1,
          width = 20,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          class = "",
          shape = "ellipse",
          x = 354,
          y = 70,
          width = 36,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          class = "",
          shape = "ellipse",
          x = 369,
          y = 150,
          width = 13,
          height = 13,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          class = "",
          shape = "ellipse",
          x = 394,
          y = 174,
          width = 17,
          height = 17,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          class = "",
          shape = "ellipse",
          x = 449,
          y = 209,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          class = "",
          shape = "ellipse",
          x = 492,
          y = 192,
          width = 18,
          height = 18,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          class = "",
          shape = "ellipse",
          x = 467,
          y = 128,
          width = 12,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          class = "",
          shape = "ellipse",
          x = 407,
          y = 77,
          width = 20,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          class = "",
          shape = "ellipse",
          x = 453,
          y = 65,
          width = 17,
          height = 17,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          class = "",
          shape = "ellipse",
          x = 438,
          y = -43,
          width = 7,
          height = 7,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          class = "",
          shape = "ellipse",
          x = 377,
          y = -91,
          width = 20,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          class = "",
          shape = "ellipse",
          x = 396,
          y = -137,
          width = 30,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          class = "",
          shape = "ellipse",
          x = 434,
          y = -124,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          class = "",
          shape = "ellipse",
          x = 484,
          y = -85,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          class = "",
          shape = "ellipse",
          x = 540,
          y = -95,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          class = "",
          shape = "ellipse",
          x = 596,
          y = -113,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          class = "",
          shape = "ellipse",
          x = 628,
          y = -102,
          width = 29,
          height = 29,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          class = "",
          shape = "ellipse",
          x = 680,
          y = -120,
          width = 9,
          height = 9,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          class = "",
          shape = "ellipse",
          x = 696,
          y = -126,
          width = 33,
          height = 33,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          class = "",
          shape = "ellipse",
          x = 616,
          y = -176,
          width = 14,
          height = 14,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          class = "",
          shape = "ellipse",
          x = 562,
          y = -193,
          width = 27,
          height = 27,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          class = "",
          shape = "ellipse",
          x = 518,
          y = -164,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          class = "",
          shape = "ellipse",
          x = 515,
          y = -113,
          width = 18,
          height = 18,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          class = "",
          shape = "ellipse",
          x = 470,
          y = -137,
          width = 12,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          class = "",
          shape = "ellipse",
          x = 464,
          y = -162,
          width = 10,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          class = "",
          shape = "ellipse",
          x = 472,
          y = -198,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          class = "",
          shape = "ellipse",
          x = 485,
          y = -232,
          width = 15,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          class = "",
          shape = "ellipse",
          x = 512,
          y = -250,
          width = 30,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          class = "",
          shape = "ellipse",
          x = 550,
          y = -247,
          width = 10,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          class = "",
          shape = "ellipse",
          x = 573,
          y = -284,
          width = 12,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          class = "",
          shape = "ellipse",
          x = 564,
          y = -320,
          width = 22,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          class = "",
          shape = "ellipse",
          x = 527,
          y = -342,
          width = 30,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          class = "",
          shape = "ellipse",
          x = 486,
          y = -316,
          width = 21,
          height = 21,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          class = "",
          shape = "ellipse",
          x = 449,
          y = -275,
          width = 4,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          class = "",
          shape = "ellipse",
          x = 423,
          y = -212,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          class = "",
          shape = "ellipse",
          x = 389,
          y = -184,
          width = 9,
          height = 9,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          class = "",
          shape = "ellipse",
          x = 341,
          y = -154,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          class = "",
          shape = "ellipse",
          x = 323,
          y = -128,
          width = 14,
          height = 14,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          class = "",
          shape = "ellipse",
          x = 305,
          y = -88,
          width = 23,
          height = 23,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          class = "",
          shape = "ellipse",
          x = 286,
          y = -59,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          class = "",
          shape = "ellipse",
          x = 245,
          y = -17,
          width = 13,
          height = 13,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          class = "",
          shape = "ellipse",
          x = 207,
          y = 6,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          class = "",
          shape = "ellipse",
          x = 162,
          y = 28,
          width = 10,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          class = "",
          shape = "ellipse",
          x = 150,
          y = 62,
          width = 35,
          height = 35,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          class = "",
          shape = "ellipse",
          x = 99,
          y = 96,
          width = 12,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          class = "",
          shape = "ellipse",
          x = 50,
          y = 103,
          width = 21,
          height = 21,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          class = "",
          shape = "ellipse",
          x = -1,
          y = 126,
          width = 18,
          height = 18,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          class = "",
          shape = "ellipse",
          x = -46,
          y = 146,
          width = 4,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          class = "",
          shape = "ellipse",
          x = -44,
          y = 191,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          class = "",
          shape = "ellipse",
          x = -16,
          y = 246,
          width = 4,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          class = "",
          shape = "ellipse",
          x = 8,
          y = 280,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          class = "",
          shape = "ellipse",
          x = 29,
          y = 304,
          width = 25,
          height = 25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          class = "",
          shape = "ellipse",
          x = -72,
          y = 288,
          width = 11,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          class = "",
          shape = "ellipse",
          x = -74,
          y = 306,
          width = 34,
          height = 34,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          class = "",
          shape = "ellipse",
          x = -19,
          y = 340,
          width = 11,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          class = "",
          shape = "ellipse",
          x = -154,
          y = 295,
          width = 15,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          class = "",
          shape = "ellipse",
          x = -165,
          y = 330,
          width = 29,
          height = 29,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          class = "",
          shape = "ellipse",
          x = -121,
          y = 334,
          width = 22,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          class = "",
          shape = "ellipse",
          x = -129,
          y = 286,
          width = 17,
          height = 17,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          class = "",
          shape = "ellipse",
          x = -118,
          y = 275,
          width = 23,
          height = 23,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          class = "",
          shape = "ellipse",
          x = -136,
          y = 229,
          width = 25,
          height = 25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          class = "",
          shape = "ellipse",
          x = -198,
          y = 240,
          width = 29,
          height = 29,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          class = "",
          shape = "ellipse",
          x = -220,
          y = 244,
          width = 9,
          height = 9,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          class = "",
          shape = "ellipse",
          x = -288,
          y = 226,
          width = 36,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          class = "",
          shape = "ellipse",
          x = -348,
          y = 263,
          width = 29,
          height = 29,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          class = "",
          shape = "ellipse",
          x = -372,
          y = 298,
          width = 18,
          height = 18,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          class = "",
          shape = "ellipse",
          x = -367,
          y = 353,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          class = "",
          shape = "ellipse",
          x = -462,
          y = 300,
          width = 23,
          height = 23,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "",
          class = "",
          shape = "ellipse",
          x = -454,
          y = 298,
          width = 10,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "",
          class = "",
          shape = "ellipse",
          x = -390,
          y = 281,
          width = 9,
          height = 9,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          class = "",
          shape = "ellipse",
          x = -417,
          y = 250,
          width = 26,
          height = 26,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          class = "",
          shape = "ellipse",
          x = -435,
          y = 259,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          class = "",
          shape = "ellipse",
          x = -393,
          y = 220,
          width = 14,
          height = 14,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          class = "",
          shape = "ellipse",
          x = -382,
          y = 187,
          width = 44,
          height = 44,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "",
          class = "",
          shape = "ellipse",
          x = -326,
          y = 178,
          width = 13,
          height = 13,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          class = "",
          shape = "ellipse",
          x = -300,
          y = 154,
          width = 22,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          class = "",
          shape = "ellipse",
          x = -254,
          y = 142,
          width = 14,
          height = 14,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "",
          class = "",
          shape = "ellipse",
          x = -222,
          y = 119,
          width = 27,
          height = 27,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "",
          class = "",
          shape = "ellipse",
          x = -204,
          y = 95,
          width = 5,
          height = 5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "",
          class = "",
          shape = "ellipse",
          x = -183,
          y = 62,
          width = 20,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          class = "",
          shape = "ellipse",
          x = -141,
          y = 49,
          width = 33,
          height = 33,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 124,
          name = "",
          class = "",
          shape = "ellipse",
          x = -82,
          y = 71,
          width = 12,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "",
          class = "",
          shape = "ellipse",
          x = -66,
          y = 40,
          width = 34,
          height = 34,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 126,
          name = "",
          class = "",
          shape = "ellipse",
          x = -50,
          y = 7,
          width = 15,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 127,
          name = "",
          class = "",
          shape = "ellipse",
          x = -46,
          y = -28,
          width = 15,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "",
          class = "",
          shape = "ellipse",
          x = -16,
          y = -58,
          width = 15,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "",
          class = "",
          shape = "ellipse",
          x = 6,
          y = -68,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "",
          class = "",
          shape = "ellipse",
          x = 35,
          y = -73,
          width = 5,
          height = 5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "",
          class = "",
          shape = "ellipse",
          x = 65,
          y = -83,
          width = 46,
          height = 46,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          class = "",
          shape = "ellipse",
          x = 107,
          y = -74,
          width = 21,
          height = 21,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "",
          class = "",
          shape = "ellipse",
          x = 112,
          y = -139,
          width = 27,
          height = 27,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "",
          class = "",
          shape = "ellipse",
          x = 140,
          y = -140,
          width = 22,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 135,
          name = "",
          class = "",
          shape = "ellipse",
          x = 156,
          y = -161,
          width = 36,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "",
          class = "",
          shape = "ellipse",
          x = 200,
          y = -166,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 137,
          name = "",
          class = "",
          shape = "ellipse",
          x = 221,
          y = -174,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 138,
          name = "",
          class = "",
          shape = "ellipse",
          x = 280,
          y = -210,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 139,
          name = "",
          class = "",
          shape = "ellipse",
          x = 359,
          y = -232,
          width = 12,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 140,
          name = "",
          class = "",
          shape = "ellipse",
          x = 264,
          y = -290,
          width = 47,
          height = 47,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 141,
          name = "",
          class = "",
          shape = "ellipse",
          x = 279,
          y = -330,
          width = 5,
          height = 5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 142,
          name = "",
          class = "",
          shape = "ellipse",
          x = 285,
          y = -416,
          width = 33,
          height = 33,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 143,
          name = "",
          class = "",
          shape = "ellipse",
          x = 347,
          y = -397,
          width = 55,
          height = 55,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 144,
          name = "",
          class = "",
          shape = "ellipse",
          x = 453,
          y = -430,
          width = 19,
          height = 19,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 145,
          name = "",
          class = "",
          shape = "ellipse",
          x = 429,
          y = -458,
          width = 23,
          height = 23,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 146,
          name = "",
          class = "",
          shape = "ellipse",
          x = 392,
          y = -474,
          width = 10,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 147,
          name = "",
          class = "",
          shape = "ellipse",
          x = 380,
          y = -461,
          width = 11,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "",
          class = "",
          shape = "ellipse",
          x = 329,
          y = -454,
          width = 21,
          height = 21,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "",
          class = "",
          shape = "ellipse",
          x = 256,
          y = -420,
          width = 4,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 150,
          name = "",
          class = "",
          shape = "ellipse",
          x = 189,
          y = -412,
          width = 27,
          height = 27,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 151,
          name = "",
          class = "",
          shape = "ellipse",
          x = 176,
          y = -366,
          width = 12,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 152,
          name = "",
          class = "",
          shape = "ellipse",
          x = 153,
          y = -331,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "",
          class = "",
          shape = "ellipse",
          x = 146,
          y = -282,
          width = 20,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "",
          class = "",
          shape = "ellipse",
          x = 201,
          y = -221,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          class = "",
          shape = "ellipse",
          x = 197,
          y = -280,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 156,
          name = "",
          class = "",
          shape = "ellipse",
          x = 123,
          y = -204,
          width = 11,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "",
          class = "",
          shape = "ellipse",
          x = 78,
          y = -178,
          width = 14,
          height = 14,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 158,
          name = "",
          class = "",
          shape = "ellipse",
          x = -8,
          y = -193,
          width = 13,
          height = 13,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 159,
          name = "",
          class = "",
          shape = "ellipse",
          x = 5,
          y = -139,
          width = 18,
          height = 18,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "",
          class = "",
          shape = "ellipse",
          x = -50,
          y = -220,
          width = 38,
          height = 38,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 161,
          name = "",
          class = "",
          shape = "ellipse",
          x = -80,
          y = -212,
          width = 9,
          height = 9,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 162,
          name = "",
          class = "",
          shape = "ellipse",
          x = -103,
          y = -182,
          width = 14,
          height = 14,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "",
          class = "",
          shape = "ellipse",
          x = -166,
          y = -172,
          width = 11,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "",
          class = "",
          shape = "ellipse",
          x = -180,
          y = -143,
          width = 19,
          height = 19,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 165,
          name = "",
          class = "",
          shape = "ellipse",
          x = -217,
          y = -76,
          width = 11,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 166,
          name = "",
          class = "",
          shape = "ellipse",
          x = -207,
          y = -12,
          width = 17,
          height = 17,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "",
          class = "",
          shape = "ellipse",
          x = -144,
          y = 16,
          width = 18,
          height = 18,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "",
          class = "",
          shape = "ellipse",
          x = -92,
          y = 14,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "",
          class = "",
          shape = "ellipse",
          x = -105,
          y = -14,
          width = 9,
          height = 9,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 170,
          name = "",
          class = "",
          shape = "ellipse",
          x = -230,
          y = 42,
          width = 14,
          height = 14,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "",
          class = "",
          shape = "ellipse",
          x = -297,
          y = 67,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 172,
          name = "",
          class = "",
          shape = "ellipse",
          x = -314,
          y = 88,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "",
          class = "",
          shape = "ellipse",
          x = -340,
          y = 133,
          width = 11,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 174,
          name = "",
          class = "",
          shape = "ellipse",
          x = -409,
          y = 115,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 175,
          name = "",
          class = "",
          shape = "ellipse",
          x = -440,
          y = 85,
          width = 30,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 176,
          name = "",
          class = "",
          shape = "ellipse",
          x = -450,
          y = 58,
          width = 29,
          height = 29,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "",
          class = "",
          shape = "ellipse",
          x = -421,
          y = 22,
          width = 11,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "",
          class = "",
          shape = "ellipse",
          x = -406,
          y = -11,
          width = 27,
          height = 27,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 179,
          name = "",
          class = "",
          shape = "ellipse",
          x = -418,
          y = -59,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 180,
          name = "",
          class = "",
          shape = "ellipse",
          x = -416,
          y = -100,
          width = 23,
          height = 23,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "",
          class = "",
          shape = "ellipse",
          x = -369,
          y = -102,
          width = 55,
          height = 55,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 182,
          name = "",
          class = "",
          shape = "ellipse",
          x = -306,
          y = -122,
          width = 22,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "",
          class = "",
          shape = "ellipse",
          x = -255,
          y = -162,
          width = 20,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 184,
          name = "",
          class = "",
          shape = "ellipse",
          x = -232,
          y = -178,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "",
          class = "",
          shape = "ellipse",
          x = -198,
          y = -220,
          width = 30,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 186,
          name = "",
          class = "",
          shape = "ellipse",
          x = -147,
          y = -264,
          width = 33,
          height = 33,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 187,
          name = "",
          class = "",
          shape = "ellipse",
          x = -102,
          y = -272,
          width = 9,
          height = 9,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "",
          class = "",
          shape = "ellipse",
          x = -52,
          y = -322,
          width = 20,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "",
          class = "",
          shape = "ellipse",
          x = -2,
          y = -342,
          width = 26,
          height = 26,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 190,
          name = "",
          class = "",
          shape = "ellipse",
          x = 30,
          y = -360,
          width = 21,
          height = 21,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 191,
          name = "",
          class = "",
          shape = "ellipse",
          x = 110,
          y = -400,
          width = 22,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 192,
          name = "",
          class = "",
          shape = "ellipse",
          x = 130,
          y = -418,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 193,
          name = "",
          class = "",
          shape = "ellipse",
          x = 75,
          y = -472,
          width = 74,
          height = 74,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 194,
          name = "",
          class = "",
          shape = "ellipse",
          x = 131,
          y = -516,
          width = 18,
          height = 18,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 195,
          name = "",
          class = "",
          shape = "ellipse",
          x = 62,
          y = -545,
          width = 39,
          height = 39,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 196,
          name = "",
          class = "",
          shape = "ellipse",
          x = 44,
          y = -523,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 197,
          name = "",
          class = "",
          shape = "ellipse",
          x = 4,
          y = -497,
          width = 28,
          height = 28,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 198,
          name = "",
          class = "",
          shape = "ellipse",
          x = -3,
          y = -451,
          width = 31,
          height = 31,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 199,
          name = "",
          class = "",
          shape = "ellipse",
          x = -16,
          y = -414,
          width = 23,
          height = 23,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 200,
          name = "",
          class = "",
          shape = "ellipse",
          x = -88,
          y = -362,
          width = 18,
          height = 18,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 201,
          name = "",
          class = "",
          shape = "ellipse",
          x = -130,
          y = -342,
          width = 20,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 202,
          name = "",
          class = "",
          shape = "ellipse",
          x = -172,
          y = -313,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 203,
          name = "",
          class = "",
          shape = "ellipse",
          x = -186,
          y = -287,
          width = 15,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 204,
          name = "",
          class = "",
          shape = "ellipse",
          x = -207,
          y = -271,
          width = 5,
          height = 5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 205,
          name = "",
          class = "",
          shape = "ellipse",
          x = -235,
          y = -254,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 206,
          name = "",
          class = "",
          shape = "ellipse",
          x = -259,
          y = -263,
          width = 10,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 207,
          name = "",
          class = "",
          shape = "ellipse",
          x = -315,
          y = -280,
          width = 33,
          height = 33,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 208,
          name = "",
          class = "",
          shape = "ellipse",
          x = -399,
          y = -244,
          width = 27,
          height = 27,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 209,
          name = "",
          class = "",
          shape = "ellipse",
          x = -420,
          y = -208,
          width = 9,
          height = 9,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 210,
          name = "",
          class = "",
          shape = "ellipse",
          x = -424,
          y = -176,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 211,
          name = "",
          class = "",
          shape = "ellipse",
          x = -409,
          y = -142,
          width = 11,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 212,
          name = "",
          class = "",
          shape = "ellipse",
          x = -346,
          y = -152,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 213,
          name = "",
          class = "",
          shape = "ellipse",
          x = -316,
          y = -160,
          width = 21,
          height = 21,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 214,
          name = "",
          class = "",
          shape = "ellipse",
          x = -462,
          y = -134,
          width = 22,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 215,
          name = "",
          class = "",
          shape = "ellipse",
          x = -555,
          y = -119,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 216,
          name = "",
          class = "",
          shape = "ellipse",
          x = -562,
          y = -102,
          width = 23,
          height = 23,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 217,
          name = "",
          class = "",
          shape = "ellipse",
          x = -596,
          y = -142,
          width = 14,
          height = 14,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 218,
          name = "",
          class = "",
          shape = "ellipse",
          x = -550,
          y = -181,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 219,
          name = "",
          class = "",
          shape = "ellipse",
          x = -532,
          y = -233,
          width = 36,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 220,
          name = "",
          class = "",
          shape = "ellipse",
          x = -469,
          y = -263,
          width = 34,
          height = 34,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 221,
          name = "",
          class = "",
          shape = "ellipse",
          x = -403,
          y = -293,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 222,
          name = "",
          class = "",
          shape = "ellipse",
          x = -361,
          y = -356,
          width = 12,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 223,
          name = "",
          class = "",
          shape = "ellipse",
          x = -310,
          y = -383,
          width = 20,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 224,
          name = "",
          class = "",
          shape = "ellipse",
          x = -248,
          y = -401,
          width = 18,
          height = 18,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 225,
          name = "",
          class = "",
          shape = "ellipse",
          x = -234,
          y = -338,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 226,
          name = "",
          class = "",
          shape = "ellipse",
          x = -264,
          y = -312,
          width = 51,
          height = 51,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 227,
          name = "",
          class = "",
          shape = "ellipse",
          x = -310,
          y = -318,
          width = 15,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 228,
          name = "",
          class = "",
          shape = "ellipse",
          x = -208,
          y = -439,
          width = 19,
          height = 19,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 229,
          name = "",
          class = "",
          shape = "ellipse",
          x = -156,
          y = -450,
          width = 26,
          height = 26,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 230,
          name = "",
          class = "",
          shape = "ellipse",
          x = -62,
          y = -446,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 231,
          name = "",
          class = "",
          shape = "ellipse",
          x = -82,
          y = -532,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 232,
          name = "",
          class = "",
          shape = "ellipse",
          x = -39,
          y = -569,
          width = 5,
          height = 5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 233,
          name = "",
          class = "",
          shape = "ellipse",
          x = -94,
          y = -599,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 234,
          name = "",
          class = "",
          shape = "ellipse",
          x = -207,
          y = -538,
          width = 22,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 235,
          name = "",
          class = "",
          shape = "ellipse",
          x = -241,
          y = -498,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 236,
          name = "",
          class = "",
          shape = "ellipse",
          x = -454,
          y = -473,
          width = 82,
          height = 82,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 237,
          name = "",
          class = "",
          shape = "ellipse",
          x = -758,
          y = -556,
          width = 171,
          height = 171,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 238,
          name = "",
          class = "",
          shape = "ellipse",
          x = 640,
          y = -647,
          width = 199,
          height = 199,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 239,
          name = "",
          class = "",
          shape = "ellipse",
          x = 612,
          y = 230,
          width = 209,
          height = 209,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "",
          class = "",
          shape = "ellipse",
          x = 8,
          y = -792,
          width = 120,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 294,
          name = "",
          class = "",
          shape = "ellipse",
          x = 184,
          y = -552,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
